### PR TITLE
Add linode, vsphere providers

### PR DESCRIPTION
**Pull request by leodotcloud**

### CODE REVIEW

**Comment by Tejeev** [comment]
Could we get a readme.md and possibly an example terraform.tfvars?  It will add substantially to the useability.

**Comment by leodotcloud** [comment]
@Tejeev PRs are welcomed :)

**Comment by Tejeev** [comment]
> @Tejeev PRs are welcomed :)
Started one when I first posted the comment but not been able to wrap it up.
See: https://github.com/Tejeev/quickstart

**Comment by nikkelma** [comment]
Apologies this has been dangling so long - since this is the `airgap` branch I'm going to merge this in, assuming anyone needing this branch has the required domain knowledge.

**Pull request merged**
