### PR TITLE
aws: added support for a temporary token

### PR DESCRIPTION
**Pull request by mjpitz**
This change adds support for an AWS session token. When using temporary tokens, the access key and secret key are insufficient.

### CODE REVIEW

**Comment by superseb** [comment]
Sorry for the late reply, if you can rebase, this can go in.

**Comment by mjpitz** [comment]
I rebased this branch and pushed up to my remote, but it looks like that also closed this branch? Tried creating a new PR, but it won't let me.

**Comment by mjpitz** [comment]
@superseb let me know how to proceed

**Comment by superseb** [comment]
It looks like it was force pulled to match upstream and not actually rebased with your commit. You can create a new branch from current master and cherry pick your commit or create a new commit and open a PR from there.

**Pull request closed without merging**
