### PR TITLE
Update rancher terraform provider to 1.10.6

### PR DESCRIPTION
**Pull request by bashofmann**
Update rancher terraform provider to 1.10.5

### CODE REVIEW

**Comment by nikkelma** [comment]
Holding off on this one until the version stabilizes - seeing moving tags and PRs even after the registry shows a 1.10.5 release.

**Comment by bashofmann** [comment]
I bumped this to 1.10.6

**Comment by bashofmann** [comment]
Worked on my machine, but apparently there is some caching issue in the terraform registry (https://github.com/rancher/terraform-provider-rancher2/issues/516). I guess, we should not merge this until it's resolved.

**Comment by rawmind0** [comment]
Terraform registey cache issue has been addressed. Rancher2 tf provider v1.10.6 should be downloaded properly now

**Pull request merged**
